services:
  webtop:
    image: linuxserver/webtop:arch-kde-version-2025-07-12@sha256:e38f6e952db39f1b498f22b74d7c4ed9241b95b6cc3c8baf55140d4ad9823f6a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
    container_name: webtop
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
