services:
  big-bear-2fauth:
    image: 2fauth/2fauth:5.2.0 # Specifies the Docker image and version to use for 2FAuth
    container_name: big-bear-2fauth # Sets the name of the container
    volumes:
      - ${APP_DATA_DIR}/data:/2fauth # Mounts the volume for persistent data storage
    ports:
      - ${APP_PORT}:8000 # Maps the port for accessing 2FAuth from the host
    environment:
      - ASSET_URL=http://${APP_DOMAIN} # Environment variable for assets URL
      - APP_URL=http://${APP_DOMAIN} # Environment variable for application URL
    networks:
      - tipi_main_network # Connects the container to the specified network
    labels:
      # Main Traefik settings for enabling the service and defining the load balancer port
      traefik.enable: true
      traefik.http.middlewares.2fauth-web-redirect.redirectscheme.scheme: https
      traefik.http.services.2fauth.loadbalancer.server.port: 8000

      # Web router configuration for HTTP, redirects to HTTPS
      traefik.http.routers.2fauth-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.2fauth-insecure.entrypoints: web
      traefik.http.routers.2fauth-insecure.service: 2fauth
      traefik.http.routers.2fauth-insecure.middlewares: 2fauth-web-redirect

      # Websecure router configuration for HTTPS
      traefik.http.routers.2fauth.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.2fauth.entrypoints: websecure
      traefik.http.routers.2fauth.service: 2fauth
      traefik.http.routers.2fauth.tls.certresolver: myresolver

      # Local domain router for HTTP, useful for internal access without HTTPS
      traefik.http.routers.2fauth-local-insecure.rule: Host(`2fauth.${LOCAL_DOMAIN}`)
      traefik.http.routers.2fauth-local-insecure.entrypoints: web
      traefik.http.routers.2fauth-local-insecure.service: 2fauth
      traefik.http.routers.2fauth-local-insecure.middlewares: 2fauth-web-redirect

      # Local domain secure router for HTTPS
      traefik.http.routers.2fauth-local.rule: Host(`2fauth.${LOCAL_DOMAIN}`)
      traefik.http.routers.2fauth-local.entrypoints: websecure
      traefik.http.routers.2fauth-local.service: 2fauth
      traefik.http.routers.2fauth-local.tls: true # Enables TLS for the local domain

      runtipi.managed: true
