# Name of the service
name: big-bear-mumble-server
# Service configurations
services:
  mumble-server:
    # Docker image to use
    image: mumblevoip/mumble-server:v1.4.230-6
    # Name of the container
    container_name: mumble-server
    # Hostname for the container
    hostname: mumble-server
    # Restart policy
    restart: on-failure
    # Ports configuration
    ports:
      - ${APP_PORT}:64738 # TCP port mapping
      - 64738:64738/udp # UDP port mapping
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
