# Configuration for watchyourlan setup

# Name of the big-bear-watchyourlan application
name: big-bear-watchyourlan
# Service definitions for the big-bear-watchyourlan application
services:
  watchyourlan:
    # Name of the container
    container_name: watchyourlan
    # Image to be used for the container
    image: aceberg/watchyourlan:2.1.4
    # Environment variables to be used for the container
    environment:
      - IFACES="eth0"
      - TZ="UTC"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-watchyourlan/data directory to /data/WatchYourLAN inside the container
      - watchyourlan_data:/data/WatchYourLAN
    # Network mode to be used for the container
    network_mode: host
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
volumes:
  watchyourlan_data:
    name: watchyourlan_data
    driver: local
networks:
  tipi_main_network:
    external: true
