# Configuration for eufy-security-ws setup

# Name of the big-bear-eufy-security-ws application
name: big-bear-eufy-security-ws
# Service definitions for the big-bear-eufy-security-ws application
services:
  eufy-security-ws:
    # Name of the container
    container_name: eufy-security-ws
    # Image to be used for the container
    image: bropat/eufy-security-ws:1.9.3
    # Environment variables for the container
    environment:
      USERNAME: "[EUFY_USERNAME]"
      PASSWORD: "[EUFY_PASSWORD]"
      COUNTRY: "US"
      LANGUAGE: "en"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local data directory to /data inside the container
      - ${APP_DATA_DIR}/data:/data
    # Network configuration
    network_mode: host
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
