# Docker Compose configuration for BigBearCasaOS Stirling PDF Service
# This service provides a web interface for a Local hosted web based PDF editor

# Name of the big-bear-stirling-pdf application
name: big-bear-stirling-pdf
# Service definitions for the big-bear-stirling-pdf application
services:
  stirling-pdf:
    # Name of the container
    container_name: stirling-pdf
    # Image to be used for the container specifies the stirling-pdf version and source
    image: stirlingtools/stirling-pdf:1.5.0
    # Container restart policy - restarts the container unless manually stopped
    restart: unless-stopped
    # Environment variables for service configuration
    environment:
      # Set to true to download security jar (required for authentication login)
      - DOCKER_ENABLE_SECURITY=false
      # Set to true to enable login for authentication
      - SECURITY_ENABLE_LOGIN=true
      # Set the initial admin username
      - SECURITY_INITIALLOGIN_USERNAME=bigbear
      # Set the initial admin password
      - SECURITY_INITIALLOGIN_PASSWORD=4500733e-a0f8-4605-a712-fd267404956a
      # Set to true to enable CSRF protection
      - CSRF_DISABLED=false
      # Set the default locale for the application
      - DEFAULT_LOCALE=en-US
      # Download Calibre onto Stirling-PDF to enable PDF to/from book and advanced HTML conversion
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      # Define custom font libraries to install for document conversions
      - LANGS=en_US
    # Volume mappings for persistent storage and configuration
    # These mounts allow the container to interact with the host system
    volumes:
      # Required for monitoring system resources and container metrics
      - ./data/tessdata:/usr/share/tessdata # Required for extra OCR languages
      - ./data/configs:/configs
    # Map port 8080 on the host to port 8080 on the container
    ports:
      - "8080:8080"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
