services:
  websync:
    image: furier/websync:latest
    restart: unless-stopped
    working_dir: /src
    command:
      - node
      - server.js
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/websync/data
        target: /data
    container_name: websync
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
