# Configuration for excalidraw setup

# Application Name
name: big-bear-excalidraw
# Services used in the application
services:
  excalidraw:
    # Name of the container
    container_name: excalidraw
    # Docker image to be used
    image: excalidraw/excalidraw:latest
    # Restart policy for the service
    restart: unless-stopped
    # Port mappings for the service
    ports:
      - "8000:80"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
