version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    groups:
      minor-patch-dev:
        dependency-type: development
        update-types:
          - minor
          - patch

      minor-patch-prod:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    rebase-strategy: 'auto'
