# Configuration for viseron setup

# Name of the big-bear-viseron application
name: big-bear-viseron
# Service definitions for the big-bear-viseron application
services:
  viseron:
    # Name of the container
    container_name: viseron
    # Image to be used for the container
    image: roflcoopter/viseron:3.3.1
    # Container restart policy
    restart: unless-stopped
    # Shared memory size
    shm_size: "1024mb"
    # Volumes to be mounted to the container
    volumes:
      - ./data/segments:/segments
      - ./data/snapshots:/snapshots
      - ./data/thumbnails:/thumbnails
      - ./data/event_clips:/event_clips
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
    # Ports mapping between host and container
    ports:
      # Mapping port 8888 of the host to port 8888 of the container
      - "8888:8888"
    # Environment variables
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
