# Configuration for netalertx setup

# Name of the big-bear-netalertx application
name: big-bear-netalertx
# Service definitions for the big-bear-netalertx application
services:
  netalertx:
    # Name of the container
    container_name: netalertx
    # Image to be used for the container
    image: jokobsk/netalertx:25.10.1
    # Container restart policy
    restart: unless-stopped
    # Make the container privileged
    privileged: true
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/config directory to /app/config inside the container
      - netalertx_config:/app/config
      # Mounting the local /DATA/AppData/$AppID/db directory to /app/db inside the container
      - netalertx_db:/app/db
    # Environment variables
    environment:
      - TZ=UTC
      - PORT=8080
      # ❗ DANGER ZONE BELOW - Setting ALWAYS_FRESH_INSTALL=true will delete the content of the /db & /config folders
      - ALWAYS_FRESH_INSTALL=false
    # Network mode for the container
    network_mode: host
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
volumes:
  netalertx_config:
    name: netalertx_config
    driver: local
  netalertx_db:
    name: netalertx_db
    driver: local
networks:
  tipi_main_network:
    external: true
