# Configuration for lobe-chat setup

# Name of the big-bear-lobe-chat application
name: big-bear-lobe-chat
# Service definitions for the big-bear-lobe-chat application
services:
  lobe-chat:
    # Name of the container
    container_name: lobe-chat
    # Image to be used for the container
    image: lobehub/lobe-chat:1.142.7
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      - OPENAI_API_KEY=""
      - OPENAI_PROXY_URL=""
      - CUSTOM_MODELS=""
      - ACCESS_CODE=""
    # Ports mapping between host and container
    ports:
      # Mapping port 3210 of the host to port 3210 of the container
      - "${APP_PORT}:3210"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
