# Configuration for changedetection setup

# Name of the big-bear-changedetection application
name: big-bear-changedetection
# Service definitions for the big-bear-changedetection application
services:
  changedetection:
    # Name of the container
    container_name: changedetection
    # Image to be used for the container
    image: ghcr.io/dgtlmoon/changedetection.io:0.50.34
    # Container restart policy
    restart: unless-stopped
    # Ports mapping between host and container
    ports:
      # Mapping port 5000 of the host to port 5000 of the container
      - "${APP_PORT}:5000"
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/data/changedetection_datastore:/datastore
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
