# Configuration for big-bear-immich-aio-alpine setup
name: big-bear-immich-aio-alpine
# Service definitions for the big-bear-immich-aio-alpine application
services:
  # Configuration for Redis service
  big-bear-immich-redis:
    container_name: big-bear-immich-redis # Name of the running container
    image: redis:6.2.20-alpine@sha256:2185e741f4c1e7b0ea9ca1e163a3767c4270a73086b6bbea2049a7203212fb7f # patched for CVE-2025-49844
    restart: always # Policy to always restart the container if it stops
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
  # Configuration for Database service
  big-bear-immich-db:
    container_name: big-bear-immich-db # Name of the running container
    image: tensorchord/pgvecto-rs:pg14-v0.2.0 # Image to be used
    environment: # Setting environment variables
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes: # Mounting directories for persistent data storage
      - ${APP_DATA_DIR}/data/immich-aio-alpine_pgdata:/var/lib/postgresql/data
    restart: unless-stopped # Policy to always restart the container if it stops
    # CasaOS specific configuration for the database service
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
  immich-aio-alpine:
    container_name: immich-aio-alpine # Name of the running container
    image: ghcr.io/imagegenius/immich:2.0.0-alpine # Image to be used
    ports: # Mapping ports from the host OS to the container
      - ${APP_PORT}:8080
    volumes: # Mounting directories for persistent data storage
      - ${APP_DATA_DIR}/data/immich-aio-alpine_config:/config
      - ${APP_DATA_DIR}/data/immich-aio-alpine_photos:/usr/src/app/photos
      # - path_to_imports:/import:ro #optional
    environment: # Setting environment variables
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=big-bear-immich-db
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=big-bear-immich-redis
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    depends_on: # Dependencies to ensure the order of service startup
      - big-bear-immich-redis
      - big-bear-immich-db
    restart: unless-stopped # Policy to restart unless stopped
    # Networks to be attached to the container
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
networks:
  tipi_main_network:
    external: true
