services:
  duckstation:
    image: linuxserver/duckstation:version-latest@sha256:b272b36098bd40328e2496a616f49e47360ee5550e46aa2ffd7cbc8d232d5c50
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duckstation/config
        target: /config
    container_name: duckstation
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
