services:
  duckstation:
    image: linuxserver/duckstation:version-latest@sha256:872b926dd713e13f06dac7135b13fa1f3ff4bc40eaabcb3ef01d8eaa16e6d34d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duckstation/config
        target: /config
    container_name: duckstation
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
