services:
  handbrake:
    image: linuxserver/handbrake:1.11.2@sha256:70bd7825a4ef68e1d102eaface31b47c703fe4d56dc9be66e1315d8129793791
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
    container_name: handbrake
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
