services:
  azahar:
    image: linuxserver/azahar:12126.1.2@sha256:d42456be1352112b447972c97b145777fbc119d580f2612275d16e03172086d5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/azahar/config
        target: /config
    container_name: azahar
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
