# Configuration for 2fauth setup

# Application Name
name: big-bear-2fauth
# Services used in the application
services:
  2fauth:
    # Name of the container
    container_name: 2fauth
    # Docker image to be used
    image: 2fauth/2fauth:5.6.0
    # Restart policy for the service
    restart: unless-stopped
    # Port mappings for the service
    ports:
      - "${APP_PORT}:8000"
    # Network mode for the service
    network_mode: bridge
    # Volumes for the service HOST -> CONTAINER
    volumes:
      - ${APP_DATA_DIR}/data/2fauth_data:/2fauth
    # Environment variables for the service
    environment:
      - APP_URL=http://[CHANGE_TO_LAN_IP]:8000
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
