services:
  webcord:
    image: linuxserver/webcord:4.14.0@sha256:8de4b17b439fedf53ef929646099812fb5506fc17a01222bd93858b3c6c1f056
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
    container_name: webcord
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
