# Configuration for focalboard setup

# Application Name
name: big-bear-focalboard
# Services used in the application
services:
  focalboard:
    # Name of the container
    container_name: focalboard
    # Docker image to be used
    image: mattermost/focalboard:7.11.4
    # Restart policy for the service
    restart: unless-stopped
    # Port mappings for the service
    ports:
      - "${APP_PORT}:8000"
    # Network mode for the service
    network_mode: bridge
    # Volumes for the service HOST -> CONTAINER
    volumes:
      - ${APP_DATA_DIR}/data:/opt/focalboard/data
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
