services:
  librewolf:
    image: linuxserver/librewolf:156.0.1@sha256:6adfdef0802c4ccbe9c36c4c2c3df234d6824cd8e6a9600edb23f845236ac296
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LIBREWOLF_CLI: ''
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/librewolf/config
        target: /config
    container_name: librewolf
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
