services:
  pydio-cells:
    image: linuxserver/pydio-cells:5.1.0@sha256:fa339560b49539a9ca4872b94805444d0a66bd8755af4cb6978ea94f73652657
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    ports:
      - target: 8080
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
    container_name: pydio-cells
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
