services:
  pydio-cells:
    image: linuxserver/pydio-cells:5.1.0@sha256:f3142b40fec79996f065ffb5d9ab25bc293dc18d88c0e75658465e23dcabbcce
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    ports:
      - target: 8080
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
    container_name: pydio-cells
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
