services:
  scummvm:
    image: linuxserver/scummvm:2026.3.0@sha256:418ff00e4f4a331117783978e906b852c6df6bc458d5b5c919c31bad4f0a0fdc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/scummvm/config
        target: /config
    container_name: scummvm
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
