services:
  smokeping:
    image: linuxserver/smokeping:2.9.0@sha256:52ab5b6bb2cbe03e775f970ac110300964d4069917820fccdfd6db80dd5ac143
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MASTER_URL: ''
      SHARED_SECRET: ''
      CACHE_DIR: ''
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/smokeping/config
        target: /config
      - type: bind
        source: /DATA/AppData/smokeping/data
        target: /data
    container_name: smokeping
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
