# Name of the service configuration
name: big-bear-node-red
# Define the services for this configuration
services:
  node-red:
    # Docker image for the service
    image: nodered/node-red:4.1.1
    # Use the host's network stack
    network_mode: host
    # Restart policy for the service
    restart: always
    # Volume configurations for persistent storage
    volumes:
      - type: bind # Bind type volume
        source: ./data/data # Source path on the host
        target: /data # Path inside the container
    # Name of the container
    container_name: node-red
    labels:
      runtipi.managed: "true"
