# Configuration for big-bear-otel-lgtm setup

# Name of the big-bear-otel-lgtm application
name: big-bear-otel-lgtm
# Service definitions for big-bear-otel-lgtm application
services:
  otel-lgtm:
    # Name of the container
    container_name: otel-lgtm
    # Image to be used for the container
    image: grafana/otel-lgtm:0.11.14
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/data directory to /data inside the container
      - type: bind
        source: ${APP_DATA_DIR}/data
        target: /data
        bind:
          create_host_path: true
    # Ports mapping between host and container
    ports:
      # Mapping port 3000 of the host to port 3000 of the container
      - mode: ingress
        target: 3000
        published: "${APP_PORT}"
        protocol: tcp
      # Mapping port 4317 of the host to port 4317 of the container  
      - mode: ingress
        target: 4317
        published: "4317"
        protocol: tcp
      # Mapping port 4318 of the host to port 4318 of the container  
      - mode: ingress
        target: 4318
        published: "4318"
        protocol: tcp
    # Networks to be attached to the container
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
networks:
  tipi_main_network:
    external: true
