version: "3.7"
# Service definitions for the big-bear-omni-tools application
services:
  # Service name: big-bear-omni-tools
  # The `big-bear-omni-tools` service definition
  big-bear-omni-tools:
    # Name of the container
    container_name: big-bear-omni-tools

    # Image to be used for the container
    image: iib0011/omni-tools:0.4.0

    # Container restart policy
    restart: unless-stopped

    # Ports mapping between host and container
    ports:
      # Mapping port 8306 of the host to port 80 of the container
      - "${APP_PORT}:80"

    networks:
      - tipi_main_network # Connects the container to the specified network

    labels:
      # Main Traefik settings for enabling the service and defining the load balancer port
      traefik.enable: true
      traefik.http.middlewares.omni-tools-web-redirect.redirectscheme.scheme: https
      traefik.http.services.omni-tools.loadbalancer.server.port: 80

      # Web router configuration for HTTP, redirects to HTTPS
      traefik.http.routers.omni-tools-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.omni-tools-insecure.entrypoints: web
      traefik.http.routers.omni-tools-insecure.service: omni-tools
      traefik.http.routers.omni-tools-insecure.middlewares: omni-tools-web-redirect

      # Websecure router configuration for HTTPS
      traefik.http.routers.omni-tools.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.omni-tools.entrypoints: websecure
      traefik.http.routers.omni-tools.service: omni-tools
      traefik.http.routers.omni-tools.tls.certresolver: myresolver

      # Local domain router for HTTP, useful for internal access without HTTPS
      traefik.http.routers.omni-tools-local-insecure.rule: Host(`omni-tools.${LOCAL_DOMAIN}`)
      traefik.http.routers.omni-tools-local-insecure.entrypoints: web
      traefik.http.routers.omni-tools-local-insecure.service: omni-tools
      traefik.http.routers.omni-tools-local-insecure.middlewares: omni-tools-web-redirect

      # Local domain secure router for HTTPS
      traefik.http.routers.omni-tools-local.rule: Host(`omni-tools.${LOCAL_DOMAIN}`)
      traefik.http.routers.omni-tools-local.entrypoints: websecure
      traefik.http.routers.omni-tools-local.service: omni-tools
      traefik.http.routers.omni-tools-local.tls: true # Enables TLS for the local domain

      runtipi.managed: true
