services:
  ppsspp:
    image: linuxserver/ppsspp:1.20.4@sha256:947556c22803d2adc12988d3b9eb414dd10a948c45a95966138ca0f937071c55
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ppsspp/config
        target: /config
    container_name: ppsspp
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
