# Configuration for obsidian setup

# Name of the big-bear-obsidian application
name: big-bear-obsidian
# Service definitions for the big-bear-obsidian application
services:
  obsidian:
    # Name of the container
    container_name: obsidian
    # Image to be used for the container
    image: linuxserver/obsidian:1.9.14
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/config:/config
    # Ports mapping between host and container
    ports:
      - ${APP_PORT}:3000
      - 3001:3001
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
