# Configuration for big-bear-code-server setup
name: big-bear-code-server
# Service definitions for the big-bear-code-server application
services:
  code-server:
    image: linuxserver/code-server:4.105.1 # The Docker image to be used for the service
    container_name: code-server # Name of the container instance
    environment:
      - PUID=1000 # User ID under which code-server will run
      - PGID=1000 # Group ID under which code-server will run
      - TZ=UTC # Timezone for the container
      - PASSWORD=my_password # Password to access code-server
      - SUDO_PASSWORD=sudo_my_password # Password to access code-server
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - code-server_config:/config #config dir
      - code-server_projects:/projects #project dir
    ports:
      - "8080:8443" # Expose code-server's port 8080 on the host's port 8080
    restart: always # Policy to restart the container if it stops unexpectedly
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
volumes:
  code-server_config:
    name: code-server_config
    driver: local
  code-server_projects:
    name: code-server_projects
    driver: local
networks:
  tipi_main_network:
    external: true
