services:
  navidrome:
    image: deluan/navidrome:0.64.0@sha256:a384948b81bd1529986c5960169e7fc4fa00f46bde6bd517971a4c36671db2af
    container_name: navidrome
    ports:
      - "${APP_PORT}:4533"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/navidrome_music:/music:ro
    restart: unless-stopped
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
