# Configuration for dozzle setup

# Name of the big-bear-dozzle application
# Service definitions for the big-bear-dozzle application
services:
  dozzle:
    # Name of the container
    container_name: dozzle
    # Image to be used for the container
    image: amir20/dozzle:v11.2.0@sha256:db7e19fd36189823c66239894e821561cb201248af35362ec6d39a08e23ff88b
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting docker.sock to allow docker management via the container
      - /var/run/docker.sock:/var/run/docker.sock
    # Ports mapping between host and container
    ports:
      # Mapping port 8888 of the host to port 8080 of the container
      - "${APP_PORT}:8080"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
