services:
  gitqlient:
    image: linuxserver/gitqlient:1.6.3@sha256:861b55c6e86c056b5543eeb2a88845f7b29b8b5386fa5d6bb9ca73eba21332b5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
    container_name: gitqlient
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
