services:
  gitqlient:
    image: linuxserver/gitqlient:1.6.3@sha256:69d602cdd9e90633f27ecd8fccad908996983ee305ff2e511fd502a3d625c0f7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
    container_name: gitqlient
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
