services:
  winegui:
    image: linuxserver/winegui:4.4.0@sha256:33ca76d0ef972567372fac1b0238fe037092e6e30a9a4d925ad9d4b9ae6cea66
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/winegui/config
        target: /config
    container_name: winegui
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
