# Configuration for myspeed setup

# Name of the big-bear-myspeed application
name: big-bear-myspeed
# Service definitions for the big-bear-myspeed application
services:
  myspeed:
    image: germannewsmaker/myspeed:1.0.9 # Docker image to be used for the service
    ports:
      - "5216:5216" # Port mapping from host to container
    volumes:
      - myspeed_data:/myspeed/data # Mount host directory to container directory
    restart: unless-stopped # Restart policy for the service
    container_name: myspeed
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
volumes:
  myspeed_data:
    name: myspeed_data
    driver: local
networks:
  tipi_main_network:
    external: true
