# Configuration for faster-whisper setup

# Name of the big-bear-faster-whisper application
name: big-bear-faster-whisper
# Service definitions for the big-bear-faster-whisper application
services:
  faster-whisper:
    # Name of the container
    container_name: faster-whisper
    # Image to be used for the container
    image: linuxserver/faster-whisper:2.5.0
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=tiny-int8
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=en #optional
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/config directory to /config inside the container
      - ${APP_DATA_DIR}/config:/config
    # Ports mapping between host and container
    ports:
      # Mapping port 10300 of the host to port 10300 of the container
      - "${APP_PORT}:10300"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
