# Configuration for farmos setup

# Name of the big-bear-farmos application
name: big-bear-farmos
# Service definitions for the big-bear-farmos application
services:
  # MariaDB database service configuration for FarmOS
  big-bear-farmos-db:
    # Specify the container name
    container_name: big-bear-farmos-db
    # Use MariaDB version 10 image
    image: mariadb:10
    # Mount the database files to persist data
    volumes:
      - "${APP_DATA_DIR}/data/farmos_db:/var/lib/mysql"
    # Expose MariaDB port to host
    ports:
      - "3306:3306"
    # Database environment configuration
    environment:
      # Root user password
      MYSQL_ROOT_PASSWORD: 037ed96f-5f27-4fa8-bd7f-49b4a804a05c
      # Name of the database to create
      MYSQL_DATABASE: big_bear_farmos
      # Create a database user
      MYSQL_USER: farmos
      # Set the database user password
      MYSQL_PASSWORD: 037ed96f-5f27-4fa8-bd7f-49b4a804a05c
    # Health check configuration to ensure database is running properly
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    # Connect to the FarmOS network
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
  farmos:
    # Name of the container
    container_name: farmos
    # Image to be used for the container
    image: farmos/farmos:3.4.5
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local homarr/configs directory to /app/data/configs inside the container
      - ${APP_DATA_DIR}/data/farmos_sites:/opt/drupal/web/sites
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "${APP_PORT}:80"
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
networks:
  tipi_main_network:
    external: true
