services:
  rsnapshot:
    image: linuxserver/rsnapshot:1.4.5@sha256:db8b82bf8cdb8020b0c6b65abc94001c622d8c5aadc56e46edd2c5589a565730
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
    container_name: rsnapshot
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
