services:
  flycast:
    image: linuxserver/flycast:2.7.20261004@sha256:e5d9e7b56f1d2ada07ad7e61405bd86c77e54fd908882c62f4a07b9f27ce5628
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/flycast/config
        target: /config
    container_name: flycast
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
