services:
  dosbox-staging:
    image: linuxserver/dosbox-staging:0.83.0@sha256:8b1001b35ddf7bcd7b610cdfddcd0e01d8c705fb13e7e69819e83482488ba83a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dosbox-staging/config
        target: /config
    container_name: dosbox-staging
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
