services:
  grav:
    image: linuxserver/grav:2.2.3@sha256:4653d99382683c825afd972dc82f5fd7e1fcb97f1e9d2fdba9ccd2e3a49ef498
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
    container_name: grav
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
