services:
  grav:
    image: linuxserver/grav:2.1.8@sha256:20c3eb58ad9e2250cb0f836e202ff7e4b01efca97f4f344baa2a50c87ac4dc81
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
    container_name: grav
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
