# Configuration for pd3f setup

# Name of the big-bear-pd3f application
name: big-bear-pd3f
# Service definitions for the big-bear-pd3f application
services:
  # Service name: parsr
  parsr:
    image: axarev/parsr:v1.2.2
    networks:
      - big-bear-pd3f-network
    expose:
      - 3001
  # Service name: redis
  redis:
    image: redis:6.2.20-alpine@sha256:2185e741f4c1e7b0ea9ca1e163a3767c4270a73086b6bbea2049a7203212fb7f
    networks:
      - big-bear-pd3f-network
    expose:
      - 6379
  # Service name: worker
  worker:
    image: pd3f/pd3f:latest
    depends_on:
      - parsr
      - redis
    networks:
      - big-bear-pd3f-network
    volumes:
      - pd3f_cache:/root/.cache/
      - pd3f_to-ocr:/to-ocr/
      - pd3f_uploads:/uploads/
    # delete results / files after one day
    environment:
      - KEEP_RESULTS_HOURS=24
    command: ["rq", "worker", "-u", "redis://redis:6379", "--results-ttl", "86400"]
  # Service name: ocr_worker
  ocr_worker:
    image: pd3f/pd3f-ocr:latest
    networks:
      - big-bear-pd3f-network
    volumes:
      - pd3f_to-ocr:/to-ocr/
  pd3f:
    # Name of the container
    container_name: pd3f
    # Image to be used for the container
    image: pd3f/pd3f:latest
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/uploads directory to /uploads/ inside the container
      - pd3f_uploads:/uploads/
    # Ports mapping between host and container
    ports:
      # Mapping port 1616 of the host to port 5000 of the container
      - "1616:5000"
    command: ["gunicorn", "app:app", "--bind=0.0.0.0:5000"]
    # Other services that this service depends on
    depends_on:
      - redis
      - parsr
      - worker
      - ocr_worker
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
# Network definitions
networks:
  big-bear-pd3f-network:
    name: big-bear-pd3f-network
  tipi_main_network:
    external: true
volumes:
  pd3f_cache:
    name: pd3f_cache
    driver: local
  pd3f_to-ocr:
    name: pd3f_to-ocr
    driver: local
  pd3f_uploads:
    name: pd3f_uploads
    driver: local
