# Configuration for dockpeek setup

# Name of the big-bear-dockpeek application
name: big-bear-dockpeek
# Service definitions for the big-bear-dockpeek application
services:
  dockpeek:
    # Name of the container
    container_name: dockpeek
    # Image to be used for the container
    image: ghcr.io/dockpeek/dockpeek:v1.7.0
    # Environment variables
    environment:
      # Secret key for the application (change this)
      SECRET_KEY: "change_this_secret_key"
      # Username for authentication (change this)
      USERNAME: "bigbear"
      # Password for authentication (change this)
      PASSWORD: "casaos"
      # Docker host configuration
      DOCKER_HOST: "unix:///var/run/docker.sock"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Ports mapping between host and container
    ports:
      - 3420:8000
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
