services:
  yq:
    image: linuxserver/yq:4.4.0@sha256:459ea899679213d9aa951398a5461d61f24dcce7358ef02398e506a0884854ed
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yq/config
        target: /config
    container_name: yq
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
