services:
  yq:
    image: linuxserver/yq:4.2.0@sha256:e48615faad77ec144fcc52f39299f6e1873314adf05d3505fbfb9abc172f3054
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yq/config
        target: /config
    container_name: yq
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
