services:
  yaak:
    image: linuxserver/yaak:2026.8.1@sha256:552e20ac2a89c871b0ea5e48cdda6c5f8961b07f2f1d6947b786df084ea0ce14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
    container_name: yaak
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
