services:
  thunderbird:
    image: linuxserver/thunderbird:1140.16.0@sha256:e438bba5d079de2a29915e2a4590fb64ed8e0ed9ab4bddef65316a65f97dc267
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thunderbird/config
        target: /config
    container_name: thunderbird
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
