services:
  github-desktop:
    image: linuxserver/github-desktop:3.4.13@sha256:2af67286e1c584956103af417d9593272f130de8bc6aa4e218efc0c4912bd86b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
    container_name: github-desktop
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
