services:
  github-desktop:
    image: linuxserver/github-desktop:3.4.13@sha256:a663ba5d99d5c6c2b1f55ba9a5e8a198bc1a957bd910922c85e15aa29645ab0e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
    container_name: github-desktop
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
