services:
  github-desktop:
    image: linuxserver/github-desktop:3.4.13@sha256:e1465fe5867239fe1bfea4b41bdfb46af2236c8a54884565bc4f1b119a1f8137
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
    container_name: github-desktop
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
