services:
  pidgin:
    image: linuxserver/pidgin:2.14.14@sha256:bc65e4095567bbfc9f4ca224cf4123065f7ba651a94d17602d9263bd5221dc76
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
    container_name: pidgin
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
