services:
  thelounge:
    image: linuxserver/thelounge:4.5.2@sha256:8793004304efb7744792c55911fc069495ecbc04c46e6054f06c12e7a44074e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 9000
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
    container_name: thelounge
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
