services:
  thelounge:
    image: linuxserver/thelounge:4.5.2@sha256:276a04a7b203ff121c2440f3f4bdcea2f9a865ba8971b6b2f372e848c789a0f8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 9000
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
    container_name: thelounge
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
