services:
  cantinarr:
    image: ghcr.io/windoze95/cantinarr:1.0.0@sha256:4d061d80aa66f691b2071b43dafd93b604607effa3138862078a341f973e55d4
    container_name: cantinarr
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8585"
    environment:
      CANTINARR_PUSH_GATEWAY_URL: https://push.cantinarr.com
      CANTINARR_ARR_CALLBACK_URL: ""
    volumes:
      - ${APP_DATA_DIR}/config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8585/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
networks:
  tipi_main_network:
    external: true
