services:
  d2-builder:
    image: linuxserver/d2-builder:0.9.0@sha256:f2a3c7f4f14050bc50665d240b2bbab49b037dbc0fe63b46385287674dcff662
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/d2-builder/config
        target: /config
    container_name: d2-builder
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
