services:
  nova-dso-tracker:
    image: mrantonsg/nova-dso-tracker:6.6.0@sha256:92edd37285ee07cb0e10104d8ab2eae95735b11e5b9b640e12c5ca7eb9d674e2
    container_name: nova-dso-tracker
    ports:
      - "${APP_PORT}:5001"
    volumes:
      - ${APP_DATA_DIR}/instance:/app/instance
    restart: unless-stopped
    network_mode: bridge
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
