services:
  apprise-api:
    image: linuxserver/apprise-api:2.0.1@sha256:742580f9c5e8e94e8009be3406bd557c012457d00acde7684066b3f897753d52
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APPRISE_ATTACH_SIZE: ''
    ports:
      - target: 8000
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/apprise-api/config
        target: /config
      - type: bind
        source: /DATA/AppData/apprise-api/attachments
        target: /attachments
    container_name: apprise-api
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
