services:
  dokuwiki:
    image: linuxserver/dokuwiki:version-2026-07-14c@sha256:23ff93932dac6e6cad553795b50883d7f9ba906a0a58d77d26bbd85306371939
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dokuwiki/config
        target: /config
    container_name: dokuwiki
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
