# Configuration for upsnap setup

# Name of the big-bear-upsnap application
name: big-bear-upsnap
# Service definitions for the big-bear-upsnap application
services:
  # Service name: big-bear-upsnap
  # The `big-bear-upsnap` service definition
  big-bear-upsnap:
    # Name of the container
    container_name: big-bear-upsnap
    # Image to be used for the container
    image: ghcr.io/seriousm4x/upsnap:5.2.3
    # Container restart policy
    restart: unless-stopped
    # Network mode
    network_mode: host
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local ./data/pb_data directory to /app/pb_data inside the container
      - ./data/pb_data:/app/pb_data
