services:
  mysql-workbench:
    image: linuxserver/mysql-workbench:8.0.47@sha256:ce3265f003ac8daacba066d394e21c3f7b8604a0fab0df15172bdcff5061b11c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mysql-workbench/config
        target: /config
    container_name: mysql-workbench
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
