services:
  sealskin:
    image: linuxserver/sealskin:0.3.2@sha256:d959efd23b736460d3e36a86ef6d4765302693f081bc82ef08cedaeefc5769e5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOST_URL: ''
    ports:
      - target: 8443
        published: ${APP_PORT}
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
      - type: bind
        source: /DATA/AppData/sealskin/storage
        target: /storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    container_name: sealskin
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
