# Configuration for big-bear-mind setup
name: big-bear-mind
# Service definitions for the big-bear-mind application
services:
  mind:
    image: "mrcas/mind:v1.4.1"
    container_name: mind
    environment:
      - TZ=UTC
    volumes:
      - "mind_db:/app/db"
    ports:
      - "8080:8080"
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
volumes:
  mind_db:
    name: mind_db
    driver: local
networks:
  tipi_main_network:
    external: true
