# Configuration for big-bear-mind setup
name: big-bear-mind
# Service definitions for the big-bear-mind application
services:
  app:
    image: "mrcas/mind:v1.4.1"
    container_name: mind
    environment:
      - TZ=UTC
    volumes:
      - "./data/db:/app/db"
    ports:
      - "8080:8080"
