# Configuration for kopia setup

# Name of the big-bear-kopia application
name: big-bear-kopia
# Service definitions for the big-bear-kopia application
services:
  kopia:
    # Name of the container
    container_name: kopia
    # Image to be used for the container
    image: ghcr.io/thespad/kopia-server:v0.17.0-spad3
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - KOPIA_HTTPS=true # Optional
      - KOPIA_UI_USERNAME=casaos
      - KOPIA_UI_PASSWORD=casaos
      - KOPIA_PASSWORD=casaos # Repository password
      - REFRESH_INTERVAL= # Optional
    volumes:
      - ${APP_DATA_DIR}/data/kopia_config:/config
      - ${APP_DATA_DIR}/data/kopia_home:/backups/home:ro # Optional
      - /var/lib/docker/volumes:/backups/docker:ro # Optional
      - ${APP_DATA_DIR}/data/kopia_repository:/repository # Optional
      - /tmp:/tmp:shared # Optional
      - /var/run/docker.sock:/var/run/docker.sock:ro # Optional
    # Ports mapping between host and container
    ports:
      # Mapping port 51515 of the host to port 51515 of the container
      - "${APP_PORT}:51515"
    # Additional capabilities to be added to the container
    cap_add:
      - SYS_ADMIN # Optional
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
