services:
  readme-sync:
    image: linuxserver/readme-sync:84f2d0c3-ls27@sha256:195a6acb0288d92d0c485d99099b93c5f88c0753c560b169ad0e9c758ad48d5f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: ${APP_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/readme-sync/config
        target: /config
    container_name: readme-sync
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
