services:
  dolphin:
    image: linuxserver/dolphin:version-2606a@sha256:2934f9f01b98669242408c97cfd927ccf308cab108c380f5d4b8dfded5eb5055
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dolphin/config
        target: /config
    container_name: dolphin
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
