services:
  signal:
    image: linuxserver/signal:8.29.0@sha256:3eb5e94b6311a74e90b627008782b6c14cefb9167aab5f0709ff3257840e8919
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: ${APP_PORT}
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
    container_name: signal
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
