version: "3.9"
services:
  big-bear-mailpit:
    container_name: big-bear-mailpit
    image: axllent/mailpit:v1.17
    restart: unless-stopped
    ports: # Ports to expose for the app service
      - "${APP_PORT}:8025"
      - "1025:1025"
    volumes: # Volumes to mount for the app service
      - ${APP_DATA_DIR}/data/mailpit:/app/data
    environment: # Environment variables for the app service
      - TZ=UTC
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.mailpit-web-redirect.redirectscheme.scheme: https
      traefik.http.services.mailpit.loadbalancer.server.port: 8025
      # Web
      traefik.http.routers.mailpit-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mailpit-insecure.entrypoints: web
      traefik.http.routers.mailpit-insecure.service: mailpit
      traefik.http.routers.mailpit-insecure.middlewares: mailpit-web-redirect
      # Websecure
      traefik.http.routers.mailpit.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mailpit.entrypoints: websecure
      traefik.http.routers.mailpit.service: mailpit
      traefik.http.routers.mailpit.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.mailpit-local-insecure.rule: Host(`mailpit.${LOCAL_DOMAIN}`)
      traefik.http.routers.mailpit-local-insecure.entrypoints: web
      traefik.http.routers.mailpit-local-insecure.service: mailpit
      traefik.http.routers.mailpit-local-insecure.middlewares: mailpit-web-redirect
      # Local domain secure
      traefik.http.routers.mailpit-local.rule: Host(`mailpit.${LOCAL_DOMAIN}`)
      traefik.http.routers.mailpit-local.entrypoints: websecure
      traefik.http.routers.mailpit-local.service: mailpit
      traefik.http.routers.mailpit-local.tls: true

      runtipi.managed: true
