# Configuration for big-bear-wordpress setup

# Name of the big-bear-wordpress application
name: big-bear-wordpress
# Service definitions for the wordpress application
services:
  # Service definition for the database
  db:
    # Docker image to use for the database
    image: mysql:5.7
    # Environment variables for the database
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      MYSQL_ROOT_PASSWORD: casaos
    # Volume mapping for the database
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_mysql:/var/lib/mysql
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
  wordpress:
    # Docker image to use for the application
    image: wordpress:6.8.3
    # Port mapping for the application
    ports:
      - ${APP_PORT}:80
    # Environment variables for the application
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: casaos
      WORDPRESS_DB_PASSWORD: casaos
      WORDPRESS_DB_NAME: wordpress
    # Volume mapping for the application
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_html:/var/www/html
    # Service dependencies for the application
    depends_on:
      - db
    container_name: wordpress
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
